services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: budgetbuddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"

  app:
    image: rkishorekumar/budgetbuddy:latest
    ports:
      - "7766:7766"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/budgetbuddy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
