name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (needed for Maven build)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build jar using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Setup Docker Buildx (needed for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # rkishorekumar
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub token

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rkishorekumar/budgetbuddy:latest

      # Step 7: Deploy to EC2 (requires SSH secrets setup)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}      # EC2 public IP
          username: ${{ secrets.EC2_USER }}  # usually 'ubuntu'
          key: ${{ secrets.EC2_KEY }}        # your private key
          script: |
            cd /home/ubuntu/sms-forwarder
            docker pull rkishorekumar/budgetbuddy:latest
            docker-compose -f docker-compose-sms.yml down
            docker-compose -f docker-compose-sms.yml up -d --build
