name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rkishorekumar/budgetbuddy:latest
          no-cache: true   # ✅ always build fresh

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            # Create budget-buddy directory if it doesn't exist
            mkdir -p /home/ubuntu/budget-buddy
            cd /home/ubuntu/budget-buddy

            # Create docker-compose file
            cat > docker-compose-budget-buddy.yml << 'EOF'
            services:
              db:
                image: postgres:17
                environment:
                  POSTGRES_DB: budgetbuddy
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: mysecretpassword
                ports:
                  - "5433:5432"
            
              app:
                image: rkishorekumar/budgetbuddy:latest
                ports:
                  - "7766:7766"
                depends_on:
                  - db
                environment:
                  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/budgetbuddy
                  SPRING_DATASOURCE_USERNAME: postgres
                  SPRING_DATASOURCE_PASSWORD: mysecretpassword
            EOF

            # Pull and restart services
            docker-compose -f docker-compose-budget-buddy.yml down || true
            docker pull rkishorekumar/budgetbuddy:latest
            docker-compose -f docker-compose-budget-buddy.yml up -d
